# Generated by Django 4.2.1 on 2023-06-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_best_exclusive_latestblog_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best',
            name='url_imagen',
            field=models.CharField(null=True),
        ),
    ]
