# Generated by Django 4.2.1 on 2023-06-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_best_url_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusive',
            name='url_imagen',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='latestblog',
            name='url_imagen',
            field=models.CharField(null=True),
        ),
    ]
