# Generated by Django 4.2.1 on 2023-06-03 05:18

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_post_delete_best_delete_exclusive_delete_latestblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_pais', models.CharField(max_length=100)),
                ('url_imagen', models.CharField(null=True)),
                ('dia_prueba', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exclusive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('url_imagen', models.CharField(null=True)),
                ('valor_anterior', models.CharField(max_length=100)),
                ('valor_actualizado', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='latestBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('url_imagen', models.CharField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
