# Generated by Django 4.2.1 on 2023-06-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_best_exclusive_latestblog_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusive',
            name='created',
        ),
        migrations.RemoveField(
            model_name='exclusive',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='exclusive',
            name='modified',
        ),
    ]
